class_name DoorAreaTests
extends ConstructionTests

func check(condition: bool, description: String) -> void:
	runner.check(condition, "doors/areas: " + description)

func run(harness: SceneTree, scene: Node2D) -> void:
	runner = harness
	game = scene
	worker = game.engineer
	jobs = game.construction
	grid = game.grid
	worker.set_process(false)
	jobs.set_process(false)
	reset_case()
	var target := Vector2i(10, 5)
	check(jobs.request_door(Vector2i(6, 5)).contains("parede") and not jobs.tasks.has(Vector2i(6, 5)), "door needs an existing wall")
	check(jobs.request_door(target).contains("solicitada") and grid.walls.has(target) and not grid.doors.has(target), "installation starts as a physical task without changing wall")
	check(jobs.request_door(target).contains("tarefa") and jobs.tasks.size() == 1, "repeated installation does not duplicate")
	jobs._process(0.0)
	begin_work()
	check(absi(worker.cell.x - target.x) + absi(worker.cell.y - target.y) == 1 and worker.state_text() == "Instalando porta", "engineer installs from orthogonal neighbor")
	jobs._process(GameSettings.DOOR_INSTALL_SECONDS * 0.5)
	check(grid.walls.has(target) and not grid.doors.has(target), "wall remains during partial installation")
	jobs.cancel_active()
	check(grid.walls.has(target) and not grid.doors.has(target) and not worker.construction_busy, "cancel preserves original wall and releases engineer")
	check(jobs.request_door(target).contains("solicitada"), "installation can be requested again")
	jobs._process(0.0)
	begin_work()
	jobs._process(0.4)
	var slot := SaveSlot.new()
	var partial_path := "user://door_install_partial_%d.json" % OS.get_process_id()
	var partial_snapshot := slot.capture(game)
	check(slot.save_game(game, partial_path).contains("sucesso"), "partial door installation can be saved")
	game.reset_scenario()
	check(slot.load_game(game, partial_path).contains("sucesso") and slot.capture(game) == partial_snapshot, "partial door installation resumes at exact position and progress")
	DirAccess.remove_absolute(partial_path)
	jobs._process(GameSettings.DOOR_INSTALL_SECONDS - 0.4)
	check(grid.doors.has(target) and not grid.doors[target] and not grid.walls.has(target) and not grid.is_walkable(target), "completion converts wall to a closed door")
	check(not worker.construction_busy and jobs.tasks.is_empty(), "installation completes once and frees worker")
	check(grid.set_door_open(target, true) and grid.is_walkable(target), "opening door allows passage")
	check(not grid.add_wall(target) and jobs.plan(target).contains("parede"), "open door cannot be overwritten by wall blueprint")
	check(grid.set_door_open(target, false) and not grid.is_walkable(target), "closing door blocks passage")
	game.select_cell(target)
	check(game.hud.cell_label.text.contains("Porta fechada") and not game.hud.toggle_door_button.disabled, "panel describes selected closed door")
	game.toggle_selected_door()
	check(grid.doors[target] and game.hud.cell_label.text.contains("Porta aberta"), "panel opens selected door and updates state")
	game.toggle_selected_door()
	check(not grid.doors[target], "panel closes selected door")
	check(jobs.request_demolition(target).contains("solicitada") and grid.doors.has(target), "door demolition waits for physical work")
	jobs._process(0.0)
	begin_work()
	jobs._process(GameSettings.WALL_DEMOLISH_SECONDS)
	check(not grid.doors.has(target) and grid.is_walkable(target), "demolition removes door and opens floor")

	# A full barrier makes the door the only route between left and right.
	reset_case()
	for y in GameSettings.GRID_SIZE.y:
		grid.walls[Vector2i(10, y)] = true
	grid.changed.emit()
	check(grid.install_door(Vector2i(10, 12)), "fixture installs closed door in barrier")
	var left := Vector2i(9, 12)
	var right := Vector2i(11, 12)
	check(GridNavigation.find_path(grid, left, right).is_empty(), "closed door blocks only passage")
	jobs.plan(right)
	jobs.authorize()
	jobs._process(0.0)
	check(jobs.tasks[right].status == "Bloqueada", "work beyond closed door reports blocked")
	check(grid.set_door_open(Vector2i(10, 12), true), "door opens by grid action")
	check(not GridNavigation.find_path(grid, left, right).is_empty(), "open door creates route")
	jobs._process(0.0)
	check(jobs.active == right and worker.construction_busy, "opening door reevaluates blocked work")
	jobs.cancel_active()
	worker._process(10.0)
	worker.set_selected(true)
	check(worker.move_to(right).contains("a caminho"), "manual route can pass open door")
	check(worker.route.has(Vector2i(10, 12)), "route includes doorway")
	check(grid.set_door_open(Vector2i(10, 12), false), "closing door changes grid")
	check(not worker.route.has(Vector2i(10, 12)), "closing door invalidates affected route")
	check(GridNavigation.find_path(grid, left, right).is_empty(), "closed door removes route again")
	check(jobs.request_demolition(Vector2i(10, 12)).contains("solicitada"), "closed door can be demolished")
	jobs._process(0.0)
	begin_work()
	jobs._process(GameSettings.WALL_DEMOLISH_SECONDS)
	check(not grid.doors.has(Vector2i(10, 12)) and not GridNavigation.find_path(grid, left, right).is_empty(), "demolishing door opens blocked route")

	reset_case()
	var floor := Vector2i(6, 6)
	check(grid.set_area(floor, 1) and grid.area_at(floor) == 1, "paint lodging on walkable cell")
	check(grid.set_area(Vector2i(7, 6), 2) and grid.set_area(Vector2i(8, 6), 3), "all initial area types can form arbitrary shapes")
	check(grid.set_area(Vector2i(10, 5), 1) == false, "painting requires walkable cell")
	check(not GridNavigation.find_path(grid, GameSettings.SPAWN, floor).is_empty(), "area does not block navigation")
	check(grid.add_wall(floor) and grid.area_at(floor) == 1 and grid.remove_wall(floor) and grid.area_at(floor) == 1, "area data stays independent when wall changes")
	game.select_cell(floor)
	check(game.hud.cell_label.text.contains("Alojamento"), "panel shows selected cell area")
	check(grid.set_area(floor, 0) and grid.area_at(floor) == 0, "no-area choice clears painted cell")
	grid.set_area(floor, 1)
	game.set_area_mode()
	var area_count := grid.areas.size()
	runner.click(runner.root, game.hud.area_button.get_global_rect().get_center(), MOUSE_BUTTON_LEFT)
	check(grid.areas.size() == area_count, "clicking area tool in panel does not paint map")
	game.area_type = 3
	game.hud.area_type.select(3)
	grid.install_door(Vector2i(10, 5))
	grid.set_door_open(Vector2i(10, 5), true)
	grid.install_door(Vector2i(10, 6))
	var path := "user://door_area_tests_%d.json" % OS.get_process_id()
	var snapshot := slot.capture(game)
	check(slot.save_game(game, path).contains("sucesso"), "save doors, areas and area tool")
	game.reset_scenario()
	check(grid.doors.is_empty() and grid.areas.is_empty(), "reset removes all doors and areas")
	check(grid.walls.has(Vector2i(10, 5)) and grid.walls.has(Vector2i(10, 6)), "reset restores original walls behind doors")
	check(slot.load_game(game, path).contains("sucesso") and slot.capture(game) == snapshot, "load restores open and closed doors, areas, tool and selection exactly")
	check(grid.doors[Vector2i(10, 5)] and not grid.doors[Vector2i(10, 6)] and grid.area_at(floor) == 1, "loaded door states and area data remain distinct")
	var invalid := snapshot.duplicate(true)
	invalid.doors[0].cell = invalid.walls[0].duplicate(true)
	var file := FileAccess.open(path, FileAccess.WRITE)
	file.store_string(JSON.stringify(invalid))
	file.close()
	check(not slot.load_game(game, path).contains("sucesso") and slot.capture(game) == snapshot, "invalid door overlap preserves existing world")
	# A schema-1 snapshot from the previous delivery remains loadable.
	game.reset_scenario()
	var legacy := slot.capture(game)
	legacy.schema_version = 1
	legacy.erase("doors")
	legacy.erase("areas")
	legacy.erase("area_type")
	legacy.erase("selected_cell")
	file = FileAccess.open(path, FileAccess.WRITE)
	file.store_string(JSON.stringify(legacy))
	file.close()
	check(slot.load_game(game, path).contains("sucesso") and grid.doors.is_empty() and grid.areas.is_empty(), "schema-1 saves from previous delivery remain readable")
	DirAccess.remove_absolute(path)
	game.reset_scenario()
