class_name ObjectTests
extends ConstructionTests

func check(condition: bool, description: String) -> void:
	runner.check(condition, "objects: " + description)

func run(harness: SceneTree, scene: Node2D) -> void:
	runner = harness
	game = scene
	worker = game.engineer
	jobs = game.construction
	grid = game.grid
	worker.set_process(false)
	jobs.set_process(false)
	var target := Vector2i(6, 5)
	for kind in range(1, GridState.OBJECT_NAMES.size()):
		reset_case()
		check(jobs.plan_object(target, kind).contains("exige área") and jobs.object_blueprints.is_empty(), "%s refuses wrong area" % GridState.OBJECT_NAMES[kind])
		grid.set_area(target, GridState.OBJECT_AREAS[kind])
		check(jobs.plan_object(target, kind).contains("Blueprint") and grid.is_walkable(target), "%s blueprint is valid and walkable" % GridState.OBJECT_NAMES[kind])
		check(jobs.plan_object(target, kind).contains("existe"), "duplicate object blueprint rejected")
		jobs.authorize()
		jobs._process(0.0)
		begin_work()
		check(absi(worker.cell.x - target.x) + absi(worker.cell.y - target.y) == 1, "installation work cell is orthogonal")
		jobs._process(GameSettings.OBJECT_INSTALL_SECONDS)
		check(grid.objects.get(target, 0) == kind and not grid.is_walkable(target) and jobs.object_blueprints.is_empty(), "%s completes as blocking object" % GridState.OBJECT_NAMES[kind])
		check(not grid.interaction_cells(target).is_empty(), "installed object has future interaction cell")
		check(grid.interaction_cells(target).has(worker.cell) and not GridNavigation.find_path(grid, GameSettings.EXIT_CELL, worker.cell).is_empty(), "interaction point remains accessible from exit")
		game.select_cell(target)
		check(game.hud.cell_label.text.contains(GridState.OBJECT_NAMES[kind]) and game.hud.cell_label.text.contains("Interação"), "selection shows object, area and interaction")
		check(jobs.plan(target).contains("ocupada") and jobs.plan_object(target, kind).contains("ocupada"), "existing object prevents conflicting blueprints")
		check(jobs.request_demolition(target).contains("solicitada") and grid.objects.has(target), "object demolition is physical")
		jobs._process(0.0)
		begin_work()
		jobs._process(GameSettings.OBJECT_DEMOLISH_SECONDS)
		check(not grid.objects.has(target) and grid.is_walkable(target), "completed demolition frees object cell")

	reset_case()
	grid.set_area(target, 1)
	jobs.plan_object(target, 1)
	check(jobs.cancel(target).contains("cancelado") and jobs.object_blueprints.is_empty() and not grid.objects.has(target), "unapproved object blueprint cancels without creation")
	jobs.plan_object(target, 1)
	jobs.authorize()
	jobs._process(0.0)
	var before := worker.position
	jobs.cancel_active()
	check(jobs.tasks.is_empty() and jobs.object_blueprints.is_empty() and not worker.construction_busy and worker.position == before, "cancel during travel removes task without teleport")
	worker._process(10.0)
	jobs.plan_object(target, 1)
	jobs.authorize()
	jobs._process(0.0)
	begin_work()
	jobs._process(0.5)
	jobs.cancel_active()
	check(jobs.tasks.is_empty() and jobs.object_blueprints.is_empty() and not grid.objects.has(target) and not worker.construction_busy, "cancel during work never creates object")
	jobs.plan_object(target, 1)
	grid.set_area(target, 2)
	jobs.authorize()
	jobs._process(0.0)
	check(jobs.tasks[target].status == "Bloqueada" and jobs.tasks[target].reason.contains("Alojamento"), "area change invalidates authorized blueprint")
	grid.set_area(target, 1)
	jobs._process(0.0)
	check(jobs.active == target, "restoring area makes blocked task eligible")
	begin_work()
	grid.set_area(target, 2)
	jobs._process(GameSettings.OBJECT_INSTALL_SECONDS)
	check(not grid.objects.has(target) and jobs.tasks[target].status == "Bloqueada", "area revalidated before completion")

	reset_case()
	worker.set_selected(true)
	worker.move_to(Vector2i(7, 5))
	worker._process(10.0)
	grid.set_area(GameSettings.EXIT_CELL, 1)
	grid.set_area(Vector2i(6, 6), 1)
	jobs.plan_object(GameSettings.EXIT_CELL, 1)
	jobs.plan_object(Vector2i(6, 6), 1)
	jobs.authorize()
	jobs._process(0.0)
	check(jobs.tasks[GameSettings.EXIT_CELL].status == "Bloqueada" and jobs.tasks[GameSettings.EXIT_CELL].reason == Construction.UNSAFE_EXIT, "object cannot block worker exit")
	check(jobs.active == Vector2i(6, 6), "blocked object does not stop accessible task")

	reset_case()
	for y in GameSettings.GRID_SIZE.y:
		grid.walls[Vector2i(10, y)] = true
	grid.changed.emit()
	grid.install_door(Vector2i(10, 12))
	grid.set_area(Vector2i(11, 12), 2)
	grid.add_object(Vector2i(11, 12), 2)
	var left := Vector2i(9, 12)
	var right := Vector2i(12, 12)
	check(GridNavigation.find_path(grid, left, right).is_empty(), "closed door and object block passage")
	grid.set_door_open(Vector2i(10, 12), true)
	check(GridNavigation.find_path(grid, left, right).is_empty(), "open door alone cannot cross blocking object")
	grid.remove_object(Vector2i(11, 12))
	check(not GridNavigation.find_path(grid, left, right).is_empty(), "open door plus removed object restores route")

	reset_case()
	var isolated_object := Vector2i(7, 7)
	grid.set_area(isolated_object, 1)
	for neighbor: Vector2i in [Vector2i(6, 7), Vector2i(7, 6), Vector2i(8, 7), Vector2i(7, 8)]:
		grid.add_wall(neighbor)
	grid.install_door(Vector2i(7, 8))
	grid.set_door_open(Vector2i(7, 8), true)
	check(grid.add_object(isolated_object, 1) and grid.interaction_cells(isolated_object) == [Vector2i(7, 8)], "open door can be the only interaction point")
	check(not grid.set_door_open(Vector2i(7, 8), false), "closing last interaction point is refused")
	grid.remove_door(Vector2i(7, 8))
	grid.set_area(Vector2i(7, 8), 1)
	check(jobs.plan(Vector2i(7, 8)).contains("interação") and jobs.plan_object(Vector2i(7, 8), 1).contains("interação"), "walls and objects cannot consume last interaction point")

	reset_case()
	grid.set_area(target, 1)
	grid.set_area(Vector2i(7, 6), 2)
	grid.set_area(Vector2i(8, 6), 2)
	grid.set_area(Vector2i(19, 19), 1)
	grid.add_object(Vector2i(7, 6), 3)
	jobs.plan_object(Vector2i(19, 19), 1)
	jobs.plan_object(target, 1)
	jobs.plan_object(Vector2i(8, 6), 4)
	jobs.authorize()
	jobs._process(0.0)
	check(jobs.tasks[Vector2i(19, 19)].status == "Bloqueada" and jobs.active == target, "mixed object queue skips blocked first task")
	begin_work()
	jobs._process(0.6)
	var slot := SaveSlot.new()
	var path := "user://object_tests_%d.json" % OS.get_process_id()
	game.set_object_mode()
	game.object_type = 4
	game.hud.object_type.select(3)
	var snapshot := slot.capture(game)
	check(slot.save_game(game, path).contains("sucesso"), "save installed object and partial installation")
	game.reset_scenario()
	check(grid.objects.is_empty() and jobs.object_blueprints.is_empty() and jobs.tasks.is_empty(), "restart removes new objects and work")
	check(slot.load_game(game, path).contains("sucesso") and slot.capture(game) == snapshot, "load restores objects, partial work, queue and tool exactly")
	check(slot.load_game(game, path).contains("sucesso") and slot.capture(game) == snapshot, "repeated load does not duplicate objects or tasks")
	check(jobs.tasks.keys() == [Vector2i(19, 19), target, Vector2i(8, 6)], "mixed task order survives repeated load")
	var invalid := snapshot.duplicate(true)
	invalid.objects[0].cell = invalid.walls[0].duplicate(true)
	var invalid_file := FileAccess.open(path, FileAccess.WRITE)
	invalid_file.store_string(JSON.stringify(invalid))
	invalid_file.close()
	check(not slot.load_game(game, path).contains("sucesso") and slot.capture(game) == snapshot, "invalid object overlap is rejected before changing world")
	jobs._process(GameSettings.OBJECT_INSTALL_SECONDS - 0.6)
	check(grid.objects.has(target) and not jobs.tasks.has(target) and jobs.tasks.size() == 2, "loaded partial object installation completes once")
	jobs.cancel_all()
	check(jobs.request_demolition(target).contains("solicitada"), "completed object can be demolished after load")
	jobs._process(0.0)
	begin_work()
	jobs._process(0.4)
	var demolition_snapshot := slot.capture(game)
	check(slot.save_game(game, path).contains("sucesso"), "partial object demolition can be saved")
	game.reset_scenario()
	check(slot.load_game(game, path).contains("sucesso") and slot.capture(game) == demolition_snapshot, "partial object demolition resumes without freeing cell")
	jobs._process(GameSettings.OBJECT_DEMOLISH_SECONDS - 0.4)
	check(not grid.objects.has(target) and jobs.tasks.is_empty(), "loaded object demolition frees cell once")
	DirAccess.remove_absolute(path)
	game.reset_scenario()
	for version in [2, 1]:
		game.reset_scenario()
		if version == 2:
			grid.set_area(Vector2i(6, 6), 1)
			grid.install_door(Vector2i(10, 5))
		var legacy := slot.capture(game)
		legacy.schema_version = version
		legacy.erase("objects")
		legacy.erase("object_blueprints")
		legacy.erase("object_type")
		if version == 1:
			legacy.erase("doors")
			legacy.erase("areas")
			legacy.erase("area_type")
			legacy.erase("selected_cell")
		var file := FileAccess.open(path, FileAccess.WRITE)
		file.store_string(JSON.stringify(legacy))
		file.close()
		check(slot.load_game(game, path).contains("sucesso") and grid.objects.is_empty() and (version == 1 or (grid.doors.has(Vector2i(10, 5)) and grid.area_at(Vector2i(6, 6)) == 1)), "schema %d save migrates without losing prior data" % version)
	DirAccess.remove_absolute(path)
	game.reset_scenario()
